#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_system?serverTimezone=UTC
    username: root
    password: root
  # thymeleaf配置
  thymeleaf:
    cache: false

#mybatis配置
mybatis:
  configuration:
    local-cache-scope: statement
    map-underscore-to-camel-case: true
  type-aliases-package: com.lagou.pojo
  mapper-locations: classpath*:/mapper/*.xml

#分页插件配置
pagehelper:
  helper-dialect: mysql